apiVersion: v1
kind: Service
metadata:
  name: personal-ai-backend-service
  namespace: personal-ai
spec:
  selector:
    app: personal-ai-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
