apiVersion: v1
kind: Service
metadata:
  name: personal-ai-frontend-service
  namespace: personal-ai
spec:
  selector:
    app: personal-ai-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
